/* 
	neighborhoods.js
*/

var downtown = {
	"name": "Royal Crest Condos",
	"units": 2,
	"vacancies": "0 Available",
	"address1": "2100 3rd Ave",
	"address2": "Seattle, WA 98121",
	"bedroom": 2,
	"bath": 2,
	"description": "This downtown apartment building is within blocks of the vibrant Seattle Center and Lower Queen Anne neighborhood. 2 2 bedroom/2 bath units are available in this building that features a rooftop pool and garden, not to mention beautiful light fixtures and hardwood floors in the units.",
	"lat": 47.613558,
	"long": -122.342212, 
	"pic": [{thumb: 'img/royal-crest/thumbs/floor.jpg', caption: 'Living Room',
			image: 'img/royal-crest/floor.jpg'},
			{thumb: 'img/royal-crest/thumbs/floor2.jpg', caption: 'Living Room',
			image: 'img/royal-crest/floor2.jpg'},
			{thumb: 'img/royal-crest/thumbs/floor3.jpg', caption: 'Living Room',
			image: 'img/royal-crest/floor3.jpg'},
			{thumb: 'img/royal-crest/thumbs/kitchen1.jpg', caption: 'Kitchen',
			image: 'img/royal-crest/kitchen1.jpg'},
			{thumb: 'img/royal-crest/thumbs/kitchen2.jpg', caption: 'Kitchen',
			image: 'img/royal-crest/kitchen2.jpg'},
			{thumb: 'img/royal-crest/thumbs/bathroom.jpg', caption: 'Bathroom',
			image: 'img/royal-crest/bathroom.jpg'},
			{thumb: 'img/royal-crest/thumbs/guest_bath.jpg', caption: 'Guest Bathroom',
			image: 'img/royal-crest/guest_bath.jpg'},
			{thumb: 'img/royal-crest/thumbs/gate.jpg', caption: 'Gate',
			image: 'img/royal-crest/gate.jpg'},
			{thumb: 'img/royal-crest/thumbs/gym.jpg', caption: 'Gym',
			image: 'img/royal-crest/gym.jpg'},
			{thumb: 'img/royal-crest/thumbs/lobby.jpg', caption: 'Lobby',
			image: 'img/royal-crest/lobby.jpg'},
			{thumb: 'img/royal-crest/thumbs/pool.jpg', caption: 'Pool',
			image: 'img/royal-crest/pool.jpg'},
			{thumb: 'img/royal-crest/thumbs/roof.jpg', caption: 'Roof',
			image: 'img/royal-crest/roof.jpg'},
			{thumb: 'img/royal-crest/thumbs/roof_garden.jpg', caption: 'Roof Garden',
			image: 'img/royal-crest/roof_garden.jpg'},
			{thumb: 'img/royal-crest/thumbs/roof_garden2.jpg', caption: 'Roof Garden',
			image: 'img/royal-crest/roof_garden2.jpg'}
	]
}

var lictonSprings = {
	"name": "Licton Springs Apartment Complex",
	"units": 6,
	"vacancies": "Unit 9208 Available in February, 2014",
	"address1": "9200 Densmore Ave N",
	"address2": "Seattle, WA 98103",
	"bedroom": "3 and 4",
	"bath": 2,
	"description": "Close to North Seattle Community College and the Northgate Mall, this 6 unit apartment building is made up of 3 and 4 bedroom / 2 bathroom units.",
	"lat": 47.696169,
	"long": -122.337271,
	"pic": [{thumb: 'img/licton-springs/thumbs/facade2.jpg', caption: 'Exterior of Apartment',
			image: 'img/licton-springs/facade2.jpg'},
			{thumb: 'img/licton-springs/thumbs/front.jpg', caption: 'Front of Apartment',
			image: 'img/licton-springs/front.jpg'},
			{thumb: 'img/licton-springs/thumbs/garden.jpg', caption: 'Garden',
			image: 'img/licton-springs/garden.jpg'},
			{thumb: 'img/licton-springs/thumbs/garden_entry.jpg', caption: 'Garden Entry',
			image: 'img/licton-springs/garden_entry.jpg'}
	]
}

var uDistrict = {
	"name": "University District Apartment Complex",
	"units": 6,
	"vacancies": "0 Available",
	"address1": "5210 11th Ave NE",
	"address2": "Seattle, WA 98115",
	"bedroom": 3,
	"bath": 1,
	"description": "Located within walking distance of the University of Washington, this charming U-District apartment building is made of 6 3 bedroom / 1 bath units. This apartment features on-site parking, hardwood floors, common areas, and breakfast counters in the kitchens.",
	"lat": 47.666817,
	"long": -122.315999,
	"pic": [{thumb: 'img/u-district/thumbs/facade2.jpg', caption: 'Exterior Close Up',
			image: 'img/u-district/facade2.jpg'},
			{thumb: 'img/u-district/thumbs/parking.jpg', caption: 'On-site Parking',
			image: 'img/u-district/parking.jpg'},
			{thumb: 'img/u-district/thumbs/dining_room.jpg', caption: 'Dining Room',
			image: 'img/u-district/dining_room.jpg'},
			{thumb: 'img/u-district/thumbs/living_room.jpg', caption: 'Living Room',
			image: 'img/u-district/living_room.jpg'},
			{thumb: 'img/u-district/thumbs/main.jpg', caption: 'Common Area',
			image: 'img/u-district/main.jpg'},
			{thumb: 'img/u-district/thumbs/kitchen.jpg', caption: 'Kitchen',
			image: 'img/u-district/kitchen.jpg'},
			{thumb: 'img/u-district/thumbs/kitchen2.jpg', caption: 'Kitchen',
			image: 'img/u-district/kitchen2.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/bedroom_floor.jpg', caption: 'Unit A - Bedroom',
			image: 'img/u-district/unit-a/bedroom_floor.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/bedroom_floor2.jpg', caption: 'Unit A - Bedroom',
			image: 'img/u-district/unit-a/bedroom_floor2.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/kitchen_unit_a.jpg', caption: 'Unit A - Kitchen',
			image: 'img/u-district/unit-a/kitchen_unit_a.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/main.jpg', caption: 'Unit A - Kitchen',
			image: 'img/u-district/unit-a/main.jpg'},
			{thumb: 'img/u-district/thumbs/kitchen_unit_b.jpg', caption: 'Unit B Kitchen',
			image: 'img/u-district/kitchen_unit_b.jpg'},
			{thumb: 'img/u-district/thumbs/kitchen_unit_c.jpg', caption: 'Unit C Kitchen',
			image: 'img/u-district/kitchen_unit_c.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/bathroom.jpg', caption: 'Unit A - Bathroom',
			image: 'img/u-district/unit-a/bathroom.jpg'},
			{thumb: 'img/u-district/unit-a/thumbs/bathroom2.jpg', caption: 'Unit A - Bathroom',
			image: 'img/u-district/unit-a/bathroom2.jpg'},
			{thumb: 'img/u-district/thumbs/bedrooms.jpg', caption: 'Bedrooms',
			image: 'img/u-district/bedrooms.jpg'}
	]
}

var westGreenlake = {
	"name": "West Greenlake Apartment Complex",
	"units": 4,
	"vacancies": "0 Available",
	"address1": "7103 Linden Ave N",
	"address2": "Seattle, WA 98103",
	"bedroom": 1,
	"bath": 1,
	"description": "Located in the charming neighborhood of North Green Lake, this 4 unit apartment is a stone’s throw from Green Lake and popular walking trails. This apartment building is made up of 1 bedroom/1 bathroom units, all featuring walnut cabinets and beautiful hardwood floors.",
	"lat": 47.680428,
	"long": -122.347590,
	"pic": [{thumb: 'img/west-greenlake/thumbs/facade1.jpg', caption: 'Exterior of Apartment',
			image: 'img/west-greenlake/facade1.jpg'},
			{thumb: 'img/west-greenlake/thumbs/bedroom.jpg', caption: 'Bedroom',
			image: 'img/west-greenlake/bedroom.jpg'},
			{thumb: 'img/west-greenlake/thumbs/dining_room.jpg', caption: 'Dining Room',
			image: 'img/west-greenlake/dining_room.jpg'},
			{thumb: 'img/west-greenlake/thumbs/dining_room2.jpg', caption: 'Dining Room',
			image: 'img/west-greenlake/dining_room2.jpg'},
			{thumb: 'img/west-greenlake/thumbs/living_room.jpg', caption: 'Living Room',
			image: 'img/west-greenlake/living_room.jpg'},
			{thumb: 'img/west-greenlake/thumbs/living_room2.jpg', caption: 'Living Room',
			image: 'img/west-greenlake/living_room2.jpg'},
			{thumb: 'img/west-greenlake/thumbs/living_room_floor.jpg', caption: 'Living Room',
			image: 'img/west-greenlake/living_room_floor.jpg'}
	]
}

var eastGreenlake = {
	"name": "East Greenlake Apartments",
	"units": 4,
	"vacancies": "0 Available",
	"address1": "7319 Woodlawn NE",
	"address2": "Seattle, WA 98115",
	"bedroom": 1,
	"bath": 1,
	"description": "Located in the fabulous neighborhood of East Green Lake, this 4 unit apartment is right in the heart of Green Lake! Right across the street from Green Lake Park, half a block away from the public library and all within walking distance of delicious restaurants and coffee shops. These 1 bedroom, 1 bathroom units feature light walnut cabinets, granite countertops and stainless steel appliances.",
	"lat": 47.681395,
	"long": -122.325818,
	"pic": [{thumb: 'img/east-greenlake/thumbs/facade_both2.jpg', caption: 'Exteriors of Apartments',
			image: 'img/east-greenlake/facade_both2.jpg'},
			{thumb: 'img/east-greenlake/thumbs/facade_both3.jpg', caption: 'Exteriors of Apartments',
			image: 'img/east-greenlake/facade_both3.jpg'},
			{thumb: 'img/east-greenlake/thumbs/facade1.jpg', caption: 'Exteriors of Apartment 7311-17',
			image: 'img/east-greenlake/facade1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/facade2.jpg', caption: 'Exteriors of Apartments 7319-25',
			image: 'img/east-greenlake/facade2.jpg'},
			{thumb: 'img/east-greenlake/thumbs/garden_entry.jpg', caption: 'Front of Apartment 7311-17',
			image: 'img/east-greenlake/garden_entry.jpg'},
			{thumb: 'img/east-greenlake/thumbs/doors.jpg', caption: 'Front Doors of Apartment 7319-25',
			image: 'img/east-greenlake/doors.jpg'},
			{thumb: 'img/east-greenlake/thumbs/doors1.jpg', caption: 'Front of Apartment 7319',
			image: 'img/east-greenlake/doors1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/wall_tenant_mural.jpg', caption: "Tenant's Mural",
			image: 'img/east-greenlake/wall_tenant_mural.jpg'},
			{thumb: 'img/east-greenlake/thumbs/living_room1.jpg', caption: 'Living Room',
			image: 'img/east-greenlake/living_room1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/living_room2.jpg', caption: 'Living Room',
			image: 'img/east-greenlake/living_room2.jpg'},
			{thumb: 'img/east-greenlake/thumbs/bedroom1.jpg', caption: 'Bedroom',
			image: 'img/east-greenlake/bedroom1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/bedroom2.jpg', caption: 'Bedroom',
			image: 'img/east-greenlake/bedroom2.jpg'},
			{thumb: 'img/east-greenlake/thumbs/bedroom3.jpg', caption: 'Bedroom',
			image: 'img/east-greenlake/bedroom3.jpg'},
			{thumb: 'img/east-greenlake/thumbs/bedroom4.jpg', caption: 'Bedroom',
			image: 'img/east-greenlake/bedroom4.jpg'},
			{thumb: 'img/east-greenlake/thumbs/kitchen1.jpg', caption: 'Kitchen',
			image: 'img/east-greenlake/kitchen1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/kitchen4.jpg', caption: 'kitchen',
			image: 'img/east-greenlake/kitchen4.jpg'},
			{thumb: 'img/east-greenlake/thumbs/bathroom1.jpg', caption: 'Bathroom',
			image: 'img/east-greenlake/bathroom1.jpg'},
			{thumb: 'img/east-greenlake/thumbs/laundry.jpg', caption: 'Laundry',
			image: 'img/east-greenlake/laundry.jpg'}

	]
}